"""Bounded, deterministic repository configuration and path-role rules.

``glossabet.json`` is repository-controlled input. Its paths are literal,
POSIX-style repository-relative prefixes: no glob expansion, filesystem
probing, or code execution. Ignore rules win; otherwise the most-specific
configured role wins over conservative built-in conventions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from glossabet.runtime.artifacts import (
    READ_ABSENT,
    READ_OVERSIZED,
    ArtifactError,
    confined_artifact_path,
    read_bounded_json,
)

CONFIG_FILE = "glossabet.json"
CONFIG_SCHEMA_VERSION = 1
MAX_CONFIG_BYTES = 1_000_000
MAX_PATH_RULES = 500
MAX_PATH_LENGTH = 512

PATH_ROLES = ("production", "test", "fixture", "generated", "vendored")
EXCLUDED_CONTENT_ROLES = frozenset({"generated", "vendored"})

# The file's shape, carried in every evidence/context ``configuration``
# section so a user or agent meets it exactly where the role classification
# is on screen. Defined beside the loader so the description cannot drift
# from what ``load_config`` accepts.
CONFIG_SHAPE = {
    "file": f"optional {CONFIG_FILE} at the scanned root",
    "schema_version": CONFIG_SCHEMA_VERSION,
    "keys": {
        "ignore_paths": "list of paths never inventoried or read",
        "path_roles": {
            role: "list of paths given this role" for role in PATH_ROLES
        },
    },
    "rules": (
        "every path is a literal /-separated prefix relative to the scanned "
        "root (no globs, absolute paths, or ..); ignore rules win; the most "
        "specific configured role wins over the built-in defaults; unknown "
        "fields or a malformed file are errors, never ignored"
    ),
    "example": {
        "schema_version": CONFIG_SCHEMA_VERSION,
        "ignore_paths": ["scratch"],
        "path_roles": {
            "production": ["tests/product_contracts"],
            "generated": ["src/api/generated"],
        },
    },
}

_TEST_DIRS = frozenset({"test", "tests", "spec", "specs", "__tests__"})
_FIXTURE_DIRS = frozenset({
    "fixture", "fixtures", "testdata", "test_data", "__snapshots__",
})
_GENERATED_DIRS = frozenset({
    "__pycache__", "_build", "build", "coverage", "dist", "generated",
    "autogenerated", "auto_generated", "out", "target",
})
_VENDORED_DIRS = frozenset({
    "_opam", "deps", "env", "node_modules", "third-party", "third_party",
    "vendor", "vendored", "venv",
})


class ConfigurationError(ArtifactError):
    """The repository configuration exists but is unsafe or malformed."""


def _matches_prefix(relative: str, prefix: str) -> bool:
    return relative == prefix or relative.startswith(prefix + "/")


def _validated_path(value: object, where: str) -> str:
    if not isinstance(value, str) or not value or value != value.strip():
        raise ConfigurationError(f"{CONFIG_FILE}: {where} must be a non-empty path")
    if len(value) > MAX_PATH_LENGTH:
        raise ConfigurationError(
            f"{CONFIG_FILE}: {where} exceeds {MAX_PATH_LENGTH} characters"
        )
    if "\\" in value:
        raise ConfigurationError(
            f"{CONFIG_FILE}: {where} must use '/' as its path separator"
        )
    if any(character in value for character in "*?["):
        raise ConfigurationError(
            f"{CONFIG_FILE}: {where} is a literal path prefix, not a glob"
        )
    if value.endswith("/"):
        raise ConfigurationError(
            f"{CONFIG_FILE}: {where} must not end with '/' (a prefix already "
            "covers the directory and everything beneath it)"
        )
    parts = value.split("/")
    if value.startswith("/") or any(part in ("", ".", "..") for part in parts):
        raise ConfigurationError(
            f"{CONFIG_FILE}: {where} must stay within the repository"
        )
    return "/".join(parts)


def _path_list(value: object, where: str) -> tuple[str, ...]:
    if not isinstance(value, list):
        raise ConfigurationError(f"{CONFIG_FILE}: {where} must be a list")
    return tuple(sorted({_validated_path(item, f"{where}[]") for item in value}))


def _default_role(relative: str, *, is_dir: bool) -> str:
    parts = relative.lower().split("/")
    directory_parts = parts if is_dir else parts[:-1]
    filename = "" if is_dir else parts[-1]
    stem = filename.rsplit(".", 1)[0]

    if any(part in _VENDORED_DIRS for part in directory_parts):
        return "vendored"
    if any(part in _GENERATED_DIRS for part in directory_parts):
        return "generated"
    if (
        not is_dir
        and (".generated." in filename or stem.endswith("_generated"))
    ):
        return "generated"
    if any(part in _FIXTURE_DIRS for part in directory_parts):
        return "fixture"
    if any(part in _TEST_DIRS for part in directory_parts):
        return "test"
    if not is_dir and (
        stem == "conftest"
        or stem.startswith("test_")
        or stem.endswith("_test")
        or stem.endswith("_tests")
        or ".test." in filename
        or ".spec." in filename
    ):
        return "test"
    return "production"


@dataclass(frozen=True)
class RepositoryConfig:
    present: bool
    ignore_paths: tuple[str, ...]
    path_roles: dict[str, tuple[str, ...]]

    def is_ignored(self, relative: str) -> bool:
        return any(_matches_prefix(relative, path) for path in self.ignore_paths)

    def role_for(self, relative: str, *, is_dir: bool = False) -> str:
        matches = [
            (path.count("/") + 1, role, path)
            for role, paths in self.path_roles.items()
            for path in paths
            if _matches_prefix(relative, path)
        ]
        if matches:
            # Exact duplicate paths across roles are rejected while loading;
            # nested rules intentionally let the most-specific prefix win.
            return max(matches, key=lambda item: item[0])[1]
        return _default_role(relative, is_dir=is_dir)

    def has_explicit_descendant(self, relative: str) -> bool:
        prefix = relative + "/"
        return any(
            path.startswith(prefix)
            for paths in self.path_roles.values()
            for path in paths
        )

    def as_evidence(self) -> dict:
        return {
            "present": self.present,
            "file": CONFIG_FILE if self.present else None,
            "schema_version": CONFIG_SCHEMA_VERSION,
            "ignore_paths": list(self.ignore_paths),
            "path_roles": {
                role: list(paths)
                for role, paths in sorted(self.path_roles.items())
                if paths
            },
            "shape": CONFIG_SHAPE,
        }


def _empty_config() -> RepositoryConfig:
    return RepositoryConfig(
        present=False,
        ignore_paths=(),
        path_roles={role: () for role in PATH_ROLES},
    )


def load_config(root: Path) -> RepositoryConfig:
    root = root.resolve()
    try:
        path = confined_artifact_path(root, CONFIG_FILE)
    except ArtifactError as exc:
        raise ConfigurationError(f"{CONFIG_FILE}: {exc}") from exc
    read = read_bounded_json(path, MAX_CONFIG_BYTES)
    if read.status == READ_ABSENT:
        return _empty_config()
    if read.status == READ_OVERSIZED:
        raise ConfigurationError(
            f"{CONFIG_FILE}: larger than {MAX_CONFIG_BYTES} bytes"
        )
    if not read.ok:
        raise ConfigurationError(f"{CONFIG_FILE}: unreadable JSON ({read.error})")
    data = read.value
    if not isinstance(data, dict):
        raise ConfigurationError(f"{CONFIG_FILE}: top level must be an object")

    allowed = {"schema_version", "ignore_paths", "path_roles"}
    unknown = sorted(set(data) - allowed)
    if unknown:
        raise ConfigurationError(
            f"{CONFIG_FILE}: unknown field(s): {', '.join(unknown)}"
        )
    version = data.get("schema_version")
    if type(version) is not int or version != CONFIG_SCHEMA_VERSION:  # not bool/float
        raise ConfigurationError(
            f"{CONFIG_FILE}: schema_version must be {CONFIG_SCHEMA_VERSION}"
        )

    ignore_paths = _path_list(data.get("ignore_paths", []), "ignore_paths")
    raw_roles = data.get("path_roles", {})
    if not isinstance(raw_roles, dict):
        raise ConfigurationError(f"{CONFIG_FILE}: path_roles must be an object")
    unknown_roles = sorted(set(raw_roles) - set(PATH_ROLES))
    if unknown_roles:
        raise ConfigurationError(
            f"{CONFIG_FILE}: unknown path role(s): {', '.join(unknown_roles)}"
        )
    path_roles = {
        role: _path_list(raw_roles.get(role, []), f"path_roles.{role}")
        for role in PATH_ROLES
    }
    rule_count = len(ignore_paths) + sum(len(paths) for paths in path_roles.values())
    if rule_count > MAX_PATH_RULES:
        raise ConfigurationError(
            f"{CONFIG_FILE}: at most {MAX_PATH_RULES} path rules are allowed"
        )

    owners: dict[str, str] = {}
    for role, paths in path_roles.items():
        for configured_path in paths:
            previous = owners.get(configured_path)
            if previous is not None:
                raise ConfigurationError(
                    f"{CONFIG_FILE}: {configured_path!r} has both {previous!r} "
                    f"and {role!r} roles"
                )
            owners[configured_path] = role

    return RepositoryConfig(
        present=True,
        ignore_paths=ignore_paths,
        path_roles=path_roles,
    )
